---
title: "fasttext_analysis"
author: "Max Chatfield"
date: '`r Sys.Date()`'
output: html_document
---

```{r}
library(readxl)
tenders <- read_excel("../../../data/UpdatedAgainTenders.xlsx", col_types = c("text", "text", "text", "text", "text", "text", "text", "date", "numeric", "text", "text", "text", "text", "numeric", "numeric", "text", "date", "date", "date", "date", "numeric", "text", "text", "text", "text", "text", "text", "text", "numeric", "numeric", "numeric", "numeric", "text", "date", "date", "text", "text"), na = c("", "NULL"))
embs <- read.csv("fasttext_emb.csv", header=FALSE)
```

# Fast Text embeddings analyasis

```{r}
pca <- prcomp(embs)
```

```{r}
library(ggplot2)
index <- seq(1:100)
cutoff <- 0.75
ggplot() + geom_line(aes(y = cumsum(pca$sdev^2) / sum(pca$sdev^2), x = index)) + geom_point(aes(y = cumsum(pca$sdev^2)/sum(pca$sdev^2), x = index)) + geom_vline(xintercept = which(cumsum(pca$sdev^2)/sum(pca$sdev^2) > cutoff)[1], col = "red")
```

```{r}
print(which(cumsum(pca$sdev^2)/sum(pca$sdev^2) > cutoff)[1])
print((cumsum(pca$sdev^2)/sum(pca$sdev^2))[2])
```

```{r}
set.seed(1337)
r.sample <- sample(seq(1:dim(pca$x)[1]), size = 10, replace = FALSE)
sub_pca <- pca$x[r.sample,1:2]
sub_tender <- tenders[r.sample,]
ggplot() + geom_point(aes(x = sub_pca[,1], y = sub_pca[,2])) + geom_text(aes(x = sub_pca[,1], y = sub_pca[,2] + 0.05, label = sub_tender$`Contract Title`))
```

```{r}
med_i <- sample(grep("med", tenders$`Contract Title`, ignore.case = TRUE), replace = FALSE)
med_tenders <- tenders[med_i,]
med_pca <- pca$x[med_i,1:2]
ggplot() + geom_point(aes(x = med_pca[,1], y = med_pca[,2], color = med_tenders$`Type of Work` == "Goods and Services")) + labs(colour="Goods and Services")
```

